
package CP.pannelli;

import CP.Taglia;

public class pnlRegistrazione extends javax.swing.JPanel {

    public pnlRegistrazione() {
        initComponents();
        // Colore di sfondo del pannello (F7F9F9 della tua palette)
        this.setBackground(new java.awt.Color(247, 249, 249));
// Stile del Bottone "Conferma"
        btnConferma.setBackground(new java.awt.Color(32, 129, 195)); // Blu scuro palette
        btnConferma.setForeground(java.awt.Color.WHITE); // Scritta bianca
        btnConferma.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
// Stile del riquadro "Camerino" (pnlModellino)
        pnlModellino.setBackground(java.awt.Color.WHITE);
        pnlModellino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 129, 195), 2));

        // Sfondo del pannello principale (quello che contiene tutto)
        this.setBackground(new java.awt.Color(247, 249, 249));
        // Stile per il "Camerino" (il pannello che hai chiamato pnlModellino)
        pnlModellino.setBackground(java.awt.Color.WHITE);
        pnlModellino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(32, 129, 195), 2));
        // Stile per il bottone di conferma
        btnConferma.setBackground(new java.awt.Color(32, 129, 195));
        btnConferma.setForeground(java.awt.Color.WHITE);
        btnConferma.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnAltezza = new javax.swing.JSpinner();
        spnPeso = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        pnlModellino = new javax.swing.JPanel();
        btnConferma = new javax.swing.JButton();
        spnEtà = new javax.swing.JSpinner();
        spnPiede = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbTaglia = new javax.swing.JComboBox<>();

        spnAltezza.setModel(new javax.swing.SpinnerNumberModel(50, 50, 250, 1));

        spnPeso.setModel(new javax.swing.SpinnerNumberModel(20, 20, 200, 1));

        jLabel3.setText("Digita la tua taglia abituale:");

        pnlModellino.setBackground(new java.awt.Color(255, 255, 255));
        pnlModellino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlModellinoLayout = new javax.swing.GroupLayout(pnlModellino);
        pnlModellino.setLayout(pnlModellinoLayout);
        pnlModellinoLayout.setHorizontalGroup(
            pnlModellinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        pnlModellinoLayout.setVerticalGroup(
            pnlModellinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnConferma.setText("Conferma registrazione");
        btnConferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfermaActionPerformed(evt);
            }
        });

        spnEtà.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        spnPiede.setModel(new javax.swing.SpinnerNumberModel(33, 15, 50, 1));

        jLabel1.setText("Digita la tua età:");

        jLabel2.setText("Digita la tua altezza:");

        jLabel4.setText("Digita il tuo peso:");

        jLabel5.setText("Digita il tuo numero di piede:");

        cmbTaglia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S ", "M", "L", "XL ", "XXL ", " ", " " }));
        cmbTaglia.setPreferredSize(new java.awt.Dimension(64, 22));
        cmbTaglia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTagliaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btnConferma))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spnPiede)
                                .addComponent(cmbTaglia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(spnEtà)
                            .addComponent(spnAltezza, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlModellino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlModellino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(spnEtà, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spnAltezza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spnPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spnPiede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbTaglia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnConferma)
                        .addGap(62, 62, 62))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfermaActionPerformed
        //  CONFERMA REGISTRAZIONE

        //  PRENDO I DATI DAI JSpinner E DAL JComboBox
        int eta = (int) spnEtà.getValue();
        int altezza = (int) spnAltezza.getValue();
        int peso = (int) spnPeso.getValue();
        int nPiede = (int) spnPiede.getValue();
        Taglia taglia = (Taglia) cmbTaglia.getSelectedItem();

        // CONTROLLARE VALIDITà DI TUTTI I DATI
        
        
        
        // SCRIVERE SUI FILE CON IL NOME COGNOME E PW

    }//GEN-LAST:event_btnConfermaActionPerformed

    private void cmbTagliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTagliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTagliaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConferma;
    private javax.swing.JComboBox<String> cmbTaglia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlModellino;
    private javax.swing.JSpinner spnAltezza;
    private javax.swing.JSpinner spnEtà;
    private javax.swing.JSpinner spnPeso;
    private javax.swing.JSpinner spnPiede;
    // End of variables declaration//GEN-END:variables
}
