/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CP.pannelli;

/**
 *
 * @author piero
 */
public class pnlSchermata1 extends javax.swing.JPanel {

    /**
     * Creates new form pnlSchermata1
     */
    public pnlSchermata1() {
        initComponents();
   // 1. Sfondo del pannello (il tuo bianco/grigio chiaro)
   this.setBackground(new java.awt.Color(247, 249, 249));
   // 2. Stile Bottone ACCEDI (Blu scuro)
   jButton1.setBackground(new java.awt.Color(32, 129, 195));
   jButton1.setForeground(java.awt.Color.WHITE);
   jButton1.setFocusPainted(false);
   jButton1.setBorderPainted(false); // Toglie il bordo brutto
   jButton1.setContentAreaFilled(true);
   jButton1.setOpaque(true);
   jButton1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
   // 3. Stile Bottone REGISTRATI (Turchese)
   jButton2.setBackground(new java.awt.Color(120, 213, 215));
   jButton2.setForeground(java.awt.Color.WHITE);
   jButton2.setFocusPainted(false);
   jButton2.setBorderPainted(false);
   jButton2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
   // 4. Modernizziamo i campi di testo (Togliamo l'effetto 3D brutto)
   javax.swing.border.Border lineBorder = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 216, 212), 1);
   jTextField2.setBorder(lineBorder);
   jTextField3.setBorder(lineBorder);
String nomeFile = "logo.jpg";
try {

    // 1. Carichiamo l'immagine

    java.net.URL imgURL = getClass().getResource("/chic/curtipasini/logo.jpg");

    if (imgURL != null) {

        javax.swing.ImageIcon iconaOriginale = new javax.swing.ImageIcon(imgURL);

        // 2. Prendi la grandezza della Label che hai disegnato tu col mouse

        int larghezzaLabel = jLabel1.getWidth();

        int altezzaLabel = jLabel1.getHeight();

        // Se la label è ancora a zero (perché l'app non è partita), diamo noi una misura base

        if(larghezzaLabel == 0) larghezzaLabel = 120;

        if(altezzaLabel == 0) altezzaLabel = 120;

        // 3. IL SEGRETO: Ridimensiona l'immagine per farla combaciare con la Label

        java.awt.Image img = iconaOriginale.getImage();

        java.awt.Image imgScalata = img.getScaledInstance(larghezzaLabel, altezzaLabel, java.awt.Image.SCALE_SMOOTH);

        // 4. Mettila nella label

        jLabel1.setIcon(new javax.swing.ImageIcon(imgScalata));

        jLabel1.setText(""); 

    }

} catch (Exception e) {

    System.out.println("Errore: " + e.getMessage());

}
// Sostituisci i nomi delle tue caselle (es. jTextField1)

jTextField3.setText("Esempio: Rossi");// Cognome
jTextField3.setForeground(java.awt.Color.GRAY);
jTextField2.setText("Esempio: Mario");// Nome 
jTextField2.setForeground(java.awt.Color.GRAY);

 // Incolla qui sotto per il tocco chic
   jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 1));
   jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 1));
   jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 1));
   jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 1));
   
  }   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(247, 249, 249));
        setForeground(new java.awt.Color(247, 249, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.setMaximumSize(new java.awt.Dimension(250, 30));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 370, 28));

        jLabel5.setText("Password");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 458, 25));

        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField3.setMaximumSize(new java.awt.Dimension(250, 30));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 370, 28));

        jButton1.setText("Accedi");
        jButton1.setMaximumSize(new java.awt.Dimension(250, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(250, 30));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 458, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Non hai un account ?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 458, -1));

        jButton2.setText("Registrati");
        jButton2.setMaximumSize(new java.awt.Dimension(250, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(250, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 458, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CP/logo.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));

        jLabel3.setText("Nome");

        jLabel4.setText("Cognome");

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       pnlRegistrazione reg = new pnlRegistrazione(); // Crea il nuovo pannello
this.getParent().add(reg); // Lo aggiunge alla finestra principale
reg.setVisible(true); // Lo rende visibile
this.setVisible(false); // Nasconde il login
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
}
